### PR TITLE
Two bug fixes

### PR DESCRIPTION
**Pull request by paulcpederson**
1. Git urls no longer cause an error
2. Check that the commit is on GitHub before trying to release

### CODE REVIEW

**Comment by paulcpederson** [comment]
If the commit isn't found on github, the following formatted error is shown in the console (with the correct project info):

```
Couldn't find the target commit on GitHub.
Make sure you've pushed everything up to paulcpederson/inline-block-grid and try again
Target commit: 3d3157ac3b0d7b036e0cbfeaa7a63ab4e6a8f2d5
```

**Comment by bcomnes** [comment]
Cool!  I'll try to check it out soon, or Nate can beat me to it.

**Comment by ngoldman** [comment]
:+1: looks good

**Comment by ngoldman** [comment]
@paulcpederson @bcomnes new release w/ the stuff we did over the last few days: https://github.com/ngoldman/gh-release/releases/tag/v1.1.2

**Comment by bcomnes** [comment]
Cool! Nice work everyone.   I already hate the test I wrote, so expect a rewrite of that soon.

**Pull request merged**
