### PR TITLE
cli: exit 1 when appropriate

### LINKED ISSUE #31: exit CLI process with 1 if release cancelled
This enables the following workflow:

```
scripts: { release: "gh-release && npm publish" }
```

meaning w/ `npm run release`, `npm publish` would only run if `gh-release` exited successfully. if answering no to final confirmation prompt, should exit with `1` to fail and end rather than going on with publish step.

make sense @paulcpederson @bcomnes?

### PR DESCRIPTION
**Pull request by ngoldman**
work in progress, may want to exit 1 for dry run as well. opinions welcome.

> fixes #31

### CODE REVIEW

**Comment by paulcpederson** [comment]
I think exiting with 0 on a dry run is good. The dry run ran successfully. That way people could discern whether there was an err in the dry run.

**Comment by ngoldman** [comment]
thanks @paulcpederson, you speak the true true.

**Comment by ngoldman** [comment]
amended and updated change log, merging when tests pass

**Comment by paulcpederson** [comment]
:ship:

**Pull request merged**
