### PR TITLE
major refactor

### PR DESCRIPTION
**Pull request by ngoldman**
Sorry for the big commit!

:construction: work in progress :construction:

This is a major refactor focused on decoupling and separation of concerns between API & CLI.

### CODE REVIEW

**Comment by ngoldman** [comment]
Taking this out of git history and dropping it in here:

---

# program flow

## current

cli

- check dir
- authenticate
- get defaults
- merge options in defaults & prune using whitelist
- defer to index

api

- check auth
- create client, add auth to client
- get defaults
- create release options
- show preview
- exit if dry run
- confirm release via prompt
- check if commit exists on remote
- attempt to create release
- exit 1 if release already exists
- return release url

## future

cli

- [x] check dir
- [x] check auth / authenticate
- [x] get defaults
- [ ] prompt for options if interactive
- [x] extend defaults with options
- [x] show preview
- [x] exit 0 if dry run
- [x] confirm release
- [x] pass options to api
- [x] callback: log err & exit 1 if commit missing on remote
- [x] callback: log err & exit 1 if release already exists
- [x] callback: log release url & exit 0

api

- [x] create client / check auth
- [x] verify release options
- [x] check if commit exists on remote (expose as method?)
- [x] attempt to create release
- [x] err if release already exists
- [x] return release url

## todos

- [x] switch from internal util._extend to deep extend module

**Comment by bcomnes** [comment]
:open_mouth: :+1:

**Comment by ngoldman** [comment]
Released the fix for #31 and rebased this PR off of master since this won't be released until v2 and there's a few more things I'd like to do from #27 before v2 is ready to go.

I'll leave the interactive mode part out of this PR for now.

@bcomnes I think this is ready to merge if it looks OK to you.

**Comment by bcomnes** [comment]
I haven't tested it, but a quick read looks good.  Go for it!

**Comment by bcomnes** [comment]
I'll refactor the tests I wrote a while back. I had a number of thigns I wanted to improve.

**Comment by ngoldman** [comment]
@bcomnes++ cool, thanks! I'll try to get more tests in soon as well

**Pull request merged**
