### PR TITLE
Replace CLI example in readme with a sweet animated GIF

### PR DESCRIPTION
**Pull request by paulcpederson**
as suggested by @paulcpederson

### CODE REVIEW

**Comment by ngoldman** [comment]
@paulcpederson said he might be down to do it as well when the time presents itself

**Comment by ngoldman** [comment]
oh, he already did.

**Comment by ngoldman** [comment]
@paulcpederson would you mind adding the image to the repo at root as `demo.gif` so it's part of the thing rather than hosted elsewheres?

**Comment by paulcpederson** [comment]
@ngoldman word

**Pull request merged**
