### PR TITLE
Added live repo test

### PR DESCRIPTION
**Pull request by bcomnes**
We should probrably unit test the indiviual functions more with mocking, but this sets up a tmp dir, and clones a repo for testing against.

### CODE REVIEW

**Comment by ngoldman** [comment]
Hey @bcomnes sorry but I didn't see this PR until I created a new release. Made some changes to getDefaults, in particular swapping out some dirty changelog parsing in favor of using http://github.com/ngoldman/changelog-parser

If you don't mind rebasing and pushing up something I can merge I'm happy to add the live repo test :)

**Comment by bcomnes** [comment]
NP, might have to wait until tonight or tomorrow.  I can clean it up and maybe even fix https://github.com/ngoldman/gh-release/issues/14

**Comment by ngoldman** [comment]
Awesome, thanks!

**Comment by ngoldman** [comment]
@bcomnes I don't mind rebasing and pulling your stuff in tomorrow if you don't get to it before then. I'll be at Bare Bones from around 2 to 6 as usual.

**Comment by bcomnes** [comment]
I'll be there but feel free to do whatever.  Been busy this week. 

--
Bret Comnes
http://bret.io

**Comment by ngoldman** [comment]
Closing as @bcomnes has requested IRL.

**Pull request closed without merging**
