### PR TITLE
Preview Styles

### PR DESCRIPTION
**Pull request by paulcpederson**
mad styles

1. Adds error if you have no repository field in `package.json`
2. Formats preview in columns
3. Colors preview with chalk
4. Automatically wraps the body using the max available console width

### CODE REVIEW

**Comment by paulcpederson** [comment]
Open to style suggestions.

**Comment by ngoldman** [comment]
No way! So cool you did that @paulcpederson.

**Comment by ngoldman** [comment]
I talked with @bcomnes and I think in the near future we should move all of the display/confirmation/CLI logic into `bin/cli.js` so the programmatic version has no CLI stuff going on but for now this works great.

**Comment by ngoldman** [comment]
fixes #15

**Pull request merged**
